# fly.toml app configuration file for park-security-flask
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'park-security-flask'
primary_region = 'gig'

[build]
  # Use only Dockerfile, not buildpacks
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# Explicitly specify the command to run
[processes]
  app = "python app.py"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[env]
  PORT = "8080"
  FLASK_ENV = "production"
  PYTHONUNBUFFERED = "1"